version=0.1

[default.deploy.parameters]
stack_name = "luissaybe-cloudfront"
s3_bucket = "cloudformation-deployments-luigi"
s3_prefix = "cloudformation-deployments-luigi"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
parameter_overrides=[
  "DomainName=luissaybe.com",
  "HostedZoneId=Z073568626TI3I5AZRPSW",
  "AcmCertificateArn=arn:aws:acm:us-east-1:264241998403:certificate/d1374949-cf69-4ac2-8d6a-4b435a8ff655"
]
